### ISSUE TITLE
Invalid/expired user token

### ISSUE THREAD

**Issue by gotnull** [kevintuhumury/dashing-fitbit#3]
No matter what I try, I'm always getting an invalid/expired user token in my widget.

I've executed the `fitbit_authorizer.rb` and can successfully generate a PIN every time, but it always returns as invalid/expired in the widget when I access `http://localhost:3030/sampletv`

**Comment by gotnull** [comment]
Clean installation:

Rails 4.1.6
Ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

# Listening on 0.0.0.0:3030, CTRL+C to stop

scheduler caught exception:
undefined method `[]' for nil:NilClass
/Users/fulvio/Projects/dashing-fitbit/lib/fitbit.rb:23:in`device'
/Users/fulvio/Projects/dashing-fitbit/jobs/fitbit.rb:13:in `block in <top (required)>'
/Users/fulvio/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in`call'
/Users/fulvio/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/Users/fulvio/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in`block in trigger'
/Users/fulvio/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/Users/fulvio/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in`block in trigger_job'

**Comment by bcongdon** [comment]
This is because Fitbit has switched entirely from OAuth to OAuth2. The gem used to authenticate with Fitbit, `Fitgem` is incompatible with Oauth2, so this widget will no longer function.

You can check out [my fork](https://github.com/bcongdon/dashing-fitbit-oauth2) - which adds OAuth2 support - if you're still interested.
